### PR TITLE
CI: Fix nested apps zip file names

### LINKED ISSUE #32: Fix handling of multi platform uploads for plugins like alexanderzobnin-zabbix-app
Context: #incident-2025-01-30-grafana-zabbix-plugin-issue
and https://raintank-corp.slack.com/archives/C024NL6AEJH/p1738249712961249?thread_ts=1738242018.844619&cid=C024NL6AEJH

You can see the file names that are being generated here https://github.com/grafana/grafana-zabbix/actions/runs/13031206731/job/36351336678#step:7:36

Usually they look like:
`grafana-github-datasource-2.0.1.darwin_amd64.zip`

and in this case it's:
`alexanderzobnin-zabbix-app-5.0.0.gpx_zabbix-datasource_windows_amd64.exe.zip` 

which makes the parsing of OS and ARCH break here:
https://github.com/grafana/plugin-ci-workflows/blob/c6fa459df1a59e805e9f9dfe3816e191c9e7712d/actions/plugins/publish/publish/publish.sh#L98-L100

We should either figure out why the zip names are different here or adjust the handling of this issue properly. 

Here is the code that does the zip file creation:
https://github.com/grafana/plugin-ci-workflows/blob/c6fa459df1a59e805e9f9dfe3816e191c9e7712d/actions/plugins/package/package.sh#L100-L123

Previously zip files were named similar to the github datasource example above: https://github.com/grafana/grafana-zabbix/releases/tag/untagged-867e38ea23f3c7ea2138

Compare files attached here: https://github.com/grafana/grafana-zabbix/releases/tag/v4.6.1 and here https://github.com/grafana/grafana-zabbix/releases/tag/untagged-867e38ea23f3c7ea2138

### PR DESCRIPTION
**Pull request by xnyo**
Fixes #32.

Fixes os/arch zip file names for nested datasources.

**Before:**

```
alexanderzobnin-zabbix-app-5.0.0.gpx_zabbix-datasource_darwin_amd64.zip
alexanderzobnin-zabbix-app-5.0.0.gpx_zabbix-datasource_darwin_arm64.zip
alexanderzobnin-zabbix-app-5.0.0.gpx_zabbix-datasource_linux_amd64.zip
alexanderzobnin-zabbix-app-5.0.0.gpx_zabbix-datasource_linux_arm64.zip
alexanderzobnin-zabbix-app-5.0.0.gpx_zabbix-datasource_linux_arm.zip
alexanderzobnin-zabbix-app-5.0.0.gpx_zabbix-datasource_windows_amd64.exe.zip
alexanderzobnin-zabbix-app-5.0.0.zip
```

**After:**
```
alexanderzobnin-zabbix-app-5.0.0.darwin_amd64.zip
alexanderzobnin-zabbix-app-5.0.0.darwin_arm64.zip
alexanderzobnin-zabbix-app-5.0.0.linux_amd64.zip
alexanderzobnin-zabbix-app-5.0.0.linux_arm64.zip
alexanderzobnin-zabbix-app-5.0.0.linux_arm.zip
alexanderzobnin-zabbix-app-5.0.0.windows_amd64.zip
alexanderzobnin-zabbix-app-5.0.0.zip
```

**Example with a non-nested app:**
```
grafana-github-datasource-2.0.1.darwin_amd64.zip
grafana-github-datasource-2.0.1.darwin_arm64.zip
grafana-github-datasource-2.0.1.linux_amd64.zip
grafana-github-datasource-2.0.1.linux_arm64.zip
grafana-github-datasource-2.0.1.linux_arm.zip
grafana-github-datasource-2.0.1.windows_amd64.zip
grafana-github-datasource-2.0.1.zip
```

**Local testing instructions:**

1. Build a nested app locally, i.e.: zabbix
2. Run the `package.sh` script without the `-u` flag to produce os/arch zip files:

```bash
./actions/plugins/package/package.sh /home/giuseppe/grafana/grafana-zabbix/dist /home/giuseppe/grafana/grafana-zabbix/artifacts
```

### CODE REVIEW

File: actions/plugins/package/package.sh [hunk 1]
```diff
@@ -53,7 +53,6 @@ fi
 mkdir -p $out
 
 cd $dist
-cat plugin.json
```
Comment (xnyo) [inline actions/plugins/package/package.sh:56]: Not related to the PR but it was a leftover from testing

**Review by s4kh — APPROVED** [review]

**Review by tolzhabayev — APPROVED** [review]

**Review by academo — APPROVED** [review]

**Review by tolzhabayev — CHANGES_REQUESTED** [review]
```
-rw-r--r--   1 timurolzhabayev  staff    53M Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_darwin_amd64.zip
-rw-r--r--   1 timurolzhabayev  staff    32B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_darwin_amd64.zip.md5
-rw-r--r--   1 timurolzhabayev  staff    40B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_darwin_amd64.zip.sha1
-rw-r--r--   1 timurolzhabayev  staff    52M Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_darwin_arm64.zip
-rw-r--r--   1 timurolzhabayev  staff    32B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_darwin_arm64.zip.md5
-rw-r--r--   1 timurolzhabayev  staff    40B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_darwin_arm64.zip.sha1
-rw-r--r--   1 timurolzhabayev  staff    53M Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_amd64.zip
-rw-r--r--   1 timurolzhabayev  staff    32B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_amd64.zip.md5
-rw-r--r--   1 timurolzhabayev  staff    40B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_amd64.zip.sha1
-rw-r--r--   1 timurolzhabayev  staff    52M Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_arm.zip
-rw-r--r--   1 timurolzhabayev  staff    32B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_arm.zip.md5
-rw-r--r--   1 timurolzhabayev  staff    40B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_arm.zip.sha1
-rw-r--r--   1 timurolzhabayev  staff    52M Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_arm64.zip
-rw-r--r--   1 timurolzhabayev  staff    32B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_arm64.zip.md5
-rw-r--r--   1 timurolzhabayev  staff    40B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.gpx_twinmaker_datasource_linux_arm64.zip.sha1
-rw-r--r--   1 timurolzhabayev  staff    53M Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.windows_amd64.exe.zip
-rw-r--r--   1 timurolzhabayev  staff    32B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.windows_amd64.exe.zip.md5
-rw-r--r--   1 timurolzhabayev  staff    40B Feb  5 10:44 grafana-iot-twinmaker-app-2.0.0.windows_amd64.exe.zip.sha1
```

this is what I get for twinmaker app, seems wrong?

Here is how it should look: https://github.com/grafana/grafana-iot-twinmaker-app/releases/tag/v2.0.0

**Comment by xnyo** [comment]
@tolzhabayev I ran it in GitHub Actions with twinmaker and it works fine: https://github.com/grafana/plugins-drone-to-gha/actions/runs/13158289213

See dist-artifacts.zip

Probably related to Mac OS, I can fix in a follow-up PR

**Review by tolzhabayev — APPROVED** [review]
